const {
  VITE_ORG_SERVICE_URL: ORG_SERVICE_URL,
  VITE_LEARNER_SERVICE_URL: LEARNER_SERVICE_URL,
  VITE_API_GATEWAY_URL: API_GATEWAY_URL,
  VITE_AUTH_REGION: AUTH_REGION,
  VITE_AUTH_USER_POOL_ID: AUTH_USER_POOL_ID,
  VITE_AUTH_USER_POOL_WEB_CLIENT_ID: AUTH_USER_POOL_WEB_CLIENT_ID,
  VITE_AI_SERVICE_URL: AI_SERVICE_URL,
  VITE_S3_FILE_PATH: S3_FILE_PATH,
} = import.meta.env;

export {
  ORG_SERVICE_URL,
  API_GATEWAY_URL,
  AUTH_REGION,
  AUTH_USER_POOL_ID,
  AUTH_USER_POOL_WEB_CLIENT_ID,
  LEARNER_SERVICE_URL,
  AI_SERVICE_URL,
  S3_FILE_PATH,
};
